### ISSUE TITLE
「大学経営の問題」について

### ISSUE THREAD

**Issue by nontan18** [nontan18/sfclt#2]
大学経営の問題：どんなにこの取り組みが継承されて拡大しても，大学経営の改善と結びつくと本文からつながらないように思える　by Koheiさん

**Comment by nontan18** [comment]
上記のように書いたが実際に支援のネットワークが過去の世代に向けて伸びるとは言い切れないので仮説の域をでないし、仮にこの仮説が成り立ったとしても、「大学経営」の成功失敗を語るには、この要素だけで判断することは困難であると考える。

全体の問題の単純化(最小限SFC-LTという奨学金システムが回るのに必要な問題のみに絞る)も考えて、「大学経営の問題」自体を本案件では取り扱わないことを提案する。

**Comment by nontangent** [comment]
MISSION完遂のための最低限の解決すべき問題を考えたとき、「大学経営の問題」を扱う必要がないという結論になったため、この問題をCloseします。
