### ISSUE TITLE
「入学競争が学生の質を向上させる」について

### ISSUE THREAD

**Issue by nontan18** [nontan18/sfclt#3]
「入学志願者が増えれば競争が激化し入学生の質が向上します.」ただ，数学と英語の偏差値が高い学生が増えるだけでは．根本的に，目的意識を持って入学するヒトを増やさない限り質は工場しなさそう． by Koheiさん

**Comment by nontangent** [comment]
「SFC-LTの講演者達がSFCの目指す理想的な学生像を示している」という仮定の上で、SFC-LTによって入学生の質は向上するといえるので、このISSUEをCloseします。
