### ISSUE TITLE
「学生全体の質が向上し社会への影響力が増せば, 企業や団体が SFC の学生を欲しがる.」について

### ISSUE THREAD

**Issue by nontan18** [nontan18/sfclt#4]
「学生全体の質が向上し社会への影響力が増せば, 企業や団体が SFC の学生を欲しがる.」について，具体的に企業が欲しがる人材を育成したい場合，LTで発表するテーマに縛りを設けたり，なにか1万円以外のインセンティブを用意したほうが良さそう． by Koheiさん

**Comment by nontan18** [comment]
確かにテーマ縛りとかをした方が企業的にうれしい気がします。ただ、逆に企業によって講演者がコントロールされすぎてしまうというのも避けたい気もしています。理念をはっきりと決めてどこまで許容するかを決めつつ、学生に何が提供できるかを企業とすり合わせて行くのが良さそう。

**Comment by nontangent** [comment]
MISSION完遂のための最低限の解決すべき問題を考えたとき、「企業・団体の人材採用」を扱う必要がないという結論になったため、この問題をCloseします。
