### ISSUE TITLE
5つの問題の解決は本当に必要か？

### ISSUE THREAD

**Issue by nontan18** [nontan18/sfclt#6]
現状、「奨学金」「大学への寄付」「大学の経営」「企業・団体へのスポンサード」「SFC」の５つの問題を同時に解決しようとしているが、それらをすべてをほんとに解決する必要があるのだろうか？

**Comment by nontan18** [comment]
SFC-LTのビジネスモデルが成り立つ上で十分条件を満たすステークホルダーは学生、湘南藤沢Projects、支援者の3者である。学生の説得のためには、彼らが問題意識を感じる「奨学金」と「SFC」の2つの問題は欠かせないとして、財源確保のために残りの問題を解決する必要があるかを考える。

現時点でSFCの奨学金制度の財源は1億円以上存在している。慶應全体への寄付も毎年60億円程度あり、このモデルの運用に必要な金額が最大でも年200万円であることを考えると、既存の大学への寄付者を説得できるだけでも十分実現可能であると考える。

**Comment by nontangent** [comment]
MISSION完遂のために最低限、解決する必要のある問題は「奨学金」「大学への寄付(者)」「SFC」の3つで十分であると判断。
